//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongTable
    {
        public int SongID { get; set; }
        public string SongName { get; set; }
        public string Lyrics { get; set; }
        public string Artist { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
